services:
    app:
        image: nginxdemos/hello
        container_name: app
        restart: unless-stopped
        networks: [ dmz ]
        expose: [ "80" ]

    waf-gateway:
        image: owasp/modsecurity-crs:nginx
        container_name: waf-gateway
        depends_on: [ app ]
        restart: unless-stopped
        ports:
            - "80:8080"
            - "443:8443"  # HTTPS exposé sur le port standard 443
        environment:
            - BACKEND=http://app:80
            - SERVER_NAME=mon-domaine.tld   # ton domaine
            - BLOCKING_PARANOIA=4
            - MODSEC_AUDIT_ENGINE=on
            - SSL_CERT=/etc/nginx/certs/server.crt
            - SSL_CERT_KEY=/etc/nginx/certs/server.key
            - NGINX_ALWAYS_TLS_REDIRECT=on  # redirection HTTP → HTTPS
        networks: [ dmz ]
        volumes:
            - ./config/waf/certs:/etc/nginx/certs:ro  # ton cert et clé en read-only

networks:
    dmz:
        driver: bridge
